version: '3'
services:
  server:
    image:
      "trenton/hugo-extended"
    ports:
      - 1313:1313
    volumes:
      - ./:/site
    tty:
      true
    command:
      hugo server -D -p 1313 --bind 0.0.0.0
    user: "${LOCALUID}:${LOCALGID}"
  
  newpost:
    image:
      "trenton/hugo-extended"
    ports:
      - 1313:1313
    user: "${LOCALUID}:${LOCALGID}"
    volumes:
      - ./:/site
    tty:
      true
    command:
      hugo new ${NAME}

  build_pages:
    image:
      "trenton/hugo-extended"
    ports:
      - 1313:1313
    user: "${LOCALUID}:${LOCALGID}"
    volumes:
      - ./:/site
    command:
      hugo --minify
