version: '3'
services:
  build_pages:
    image:
      "trenton/hugo-extended"
    ports:
      - 1313:1313
    user: "1000:1000"
    volumes:
      - $GITHUB_WORKSPACE/:/site
    command:
      hugo 
